/****************************************************************************
**
** Namespace OmniRig generated by dumpcpp v6.10.1 using
** C:\msys64\mingw64\bin\dumpcpp.exe -o OmniRig {4FE359C5-A58F-459D-BE95-CA559FB4F270}
** from the type library C:\Program Files (x86)\Afreet\OmniRig\OmniRig.exe
**
****************************************************************************/

#ifndef QAX_DUMPCPP_OMNIRIG_H
#define QAX_DUMPCPP_OMNIRIG_H

// Define this symbol to __declspec(dllexport) or __declspec(dllimport)
#ifndef OMNIRIG_EXPORT
#define OMNIRIG_EXPORT
#endif

#include <qaxobject.h>
#include <qaxwidget.h>
#include <qdatetime.h>
#include <qpixmap.h>
#include <qpoint.h>
#include <qrect.h>
#include <qsize.h>

struct IDispatch;


// Referenced namespace

namespace OmniRig {

    enum RigParamX {
        PM_UNKNOWN              = 1,
        PM_FREQ                 = 2,
        PM_FREQA                = 4,
        PM_FREQB                = 8,
        PM_PITCH                = 16,
        PM_RITOFFSET            = 32,
        PM_RIT0                 = 64,
        PM_VFOAA                = 128,
        PM_VFOAB                = 256,
        PM_VFOBA                = 512,
        PM_VFOBB                = 1024,
        PM_VFOA                 = 2048,
        PM_VFOB                 = 4096,
        PM_VFOEQUAL             = 8192,
        PM_VFOSWAP              = 16384,
        PM_SPLITON              = 32768,
        PM_SPLITOFF             = 65536,
        PM_RITON                = 131072,
        PM_RITOFF               = 262144,
        PM_XITON                = 524288,
        PM_XITOFF               = 1048576,
        PM_RX                   = 2097152,
        PM_TX                   = 4194304,
        PM_CW_U                 = 8388608,
        PM_CW_L                 = 16777216,
        PM_SSB_U                = 33554432,
        PM_SSB_L                = 67108864,
        PM_DIG_U                = 134217728,
        PM_DIG_L                = 268435456,
        PM_AM                   = 536870912,
        PM_FM                   = 1073741824
    };

    enum RigStatusX {
        ST_NOTCONFIGURED        = 0,
        ST_DISABLED             = 1,
        ST_PORTBUSY             = 2,
        ST_NOTRESPONDING        = 3,
        ST_ONLINE               = 4
    };

// forward declarations
    class IRigX;
    class IPortBits;

class OMNIRIG_EXPORT IOmniRigX : public QAxObject
{
public:
    explicit IOmniRigX(IDispatch *subobject = nullptr, QAxObject *parent = nullptr)
        : QAxObject(reinterpret_cast<IUnknown*>(subobject), parent) {}

    inline bool DialogVisible() const { return property("DialogVisible").toBool(); }
    inline void SetDialogVisible(bool value) { setProperty("DialogVisible", value); }
    inline int InterfaceVersion() const { return property("InterfaceVersion").toInt(); }
    inline OmniRig::IRigX* Rig1() const;
    inline OmniRig::IRigX* Rig2() const;
    inline int SoftwareVersion() const { return property("SoftwareVersion").toInt(); }

// meta object functions
    Q_OBJECT_FAKE
};

class OMNIRIG_EXPORT IRigX : public QAxObject
{
public:
    explicit IRigX(IDispatch *subobject = nullptr, QAxObject *parent = nullptr)
        : QAxObject(reinterpret_cast<IUnknown*>(subobject), parent) {}

    inline int GetRxFrequency() const { return property("FreqA").toInt(); }
    inline void SetFreq(int value) { setProperty("Freq", value); }
    inline void SetFreqA(int value) { setProperty("FreqA", value); }
    inline int FreqA() const { return property("FreqA").toInt(); }
    inline int FreqB() const { return property("FreqB").toInt(); }
    inline void SetFreqB(int value) { setProperty("FreqB", value); }
    inline int GetRxStatus() const { return property("RxStatus").toInt(); }
    inline int GetTxStatus() const { return property("TxStatus").toInt(); }
    inline OmniRig::RigStatusX Status() const { return static_cast<OmniRig::RigStatusX>(property("Status").toInt()); }
    inline QString StatusStr() const { return property("StatusStr").toString(); }
    inline int Freq() const { return property("Freq").toInt(); }
    inline int ReadableParams() const { return property("ReadableParams").toInt(); }
    inline int WriteableParams() const { return property("WriteableParams").toInt(); }
    inline void SetMode(OmniRig::RigParamX value) { setProperty("Mode", static_cast<int>(value)); }
    inline OmniRig::RigParamX Mode() const { return static_cast<OmniRig::RigParamX>(property("Mode").toInt()); }
    inline void SetSplit(OmniRig::RigParamX value) { setProperty("Split", static_cast<int>(value)); }
    inline void SetRit(OmniRig::RigParamX value) { setProperty("Rit", static_cast<int>(value)); }
    inline void SetXit(OmniRig::RigParamX value) { setProperty("Xit", static_cast<int>(value)); }
    inline void SetTx(OmniRig::RigParamX value) { setProperty("Tx", static_cast<int>(value)); }
    inline void SetVfo(OmniRig::RigParamX value) { setProperty("Vfo", static_cast<int>(value)); }
    inline OmniRig::RigParamX Vfo() const { return static_cast<OmniRig::RigParamX>(property("Vfo").toInt()); }
    inline QString RigType() const { return property("RigType").toString(); }
    inline IDispatch* PortBits() {
        return reinterpret_cast<IDispatch*>(querySubObject("PortBits"));
    }
    inline void SetSplitMode(int rx_freq, int tx_freq) {
        dynamicCall("SetSplitMode(int,int)", rx_freq, tx_freq);
    }
    inline void SetSimplexMode(int freq) {
        dynamicCall("SetSimplexMode(int)", freq);
    }
    inline void SendCustomCommand(QVariant const& command, int replyLength, QVariant const& replyEnd) {
        Q_UNUSED(command); Q_UNUSED(replyLength); Q_UNUSED(replyEnd);
    }

    Q_OBJECT_FAKE
};

class OMNIRIG_EXPORT IPortBits : public QAxObject
{
public:
    explicit IPortBits(IDispatch *subobject = nullptr, QAxObject *parent = nullptr)
        : QAxObject(reinterpret_cast<IUnknown*>(subobject), parent) {}

    inline int Lock() { return 0; }
    inline void Unlock() {}
    inline bool Cts() const { return property("Cts").toBool(); }
    inline bool Dsr() const { return property("Dsr").toBool(); }
    inline bool Rts() const { return property("Rts").toBool(); }
    inline bool Dtr() const { return property("Dtr").toBool(); }
    inline void SetDtr(bool value) { setProperty("Dtr", value); }
    inline void SetRts(bool value) { setProperty("Rts", value); }

    Q_OBJECT_FAKE
};

// coclass wrappers
class OMNIRIG_EXPORT OmniRigX : public IOmniRigX
{
public:
    explicit OmniRigX(QObject * /*parent*/ = nullptr)
        : IOmniRigX()
    {
        setControl(QStringLiteral("{4FE359C5-A58F-459D-BE95-CA559FB4F270}"));
    }
};

class OMNIRIG_EXPORT RigX : public IRigX
{
public:
    explicit RigX(IDispatch *subobject = nullptr, QAxObject *parent = nullptr)
        : IRigX(subobject, parent) {}
    explicit RigX(IRigX *rig, QAxObject *parent = nullptr)
        : IRigX(nullptr, parent) { Q_UNUSED(rig); }
};

class OMNIRIG_EXPORT PortBits : public IPortBits
{
public:
    explicit PortBits(IDispatch *subobject = nullptr, QAxObject *parent = nullptr)
        : IPortBits(subobject, parent) {}
};

inline OmniRig::IRigX* IOmniRigX::Rig1() const {
    return qobject_cast<OmniRig::IRigX*>(const_cast<IOmniRigX*>(this)->querySubObject("Rig1"));
}

inline OmniRig::IRigX* IOmniRigX::Rig2() const {
    return qobject_cast<OmniRig::IRigX*>(const_cast<IOmniRigX*>(this)->querySubObject("Rig2"));
}

} // namespace OmniRig

#endif // QAX_DUMPCPP_OMNIRIG_H
