FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    gfortran-aarch64-linux-gnu \
    gcc-aarch64-linux-gnu \
    g++-aarch64-linux-gnu \
    binutils-aarch64-linux-gnu \
    libboost-dev \
    wget make file \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src
ENTRYPOINT ["bash"]
